### ISSUE TITLE
TIBCO Jaspersoft Studio 6.13.0 ---- Source code cannot be compiled

### ISSUE THREAD

**Issue by gotoseeworld** [TIBCOSoftware/jaspersoft-studio-ce#23]
Hello, I downloaded the source code of the community edition of studio at https://github.com/TIBCOSoftware/jaspersoft-studio-ce, and then configured the targetrepo of eclipse normally, but part of the source code cannot be compiled.  By analyzing the POM file in the source code, it is found that the code of the following module is missing from the community edition of the code:

<module>../../net.sf.jasperreports</module>
<module>../../net.sf.jasperreports.doc</module>
<module>../../net.sf.jasperreports.samples</module>

<module>../../net.sf.jasperreports.feature</module>
<module>../../net.sf.jasperreports.samples.feature</module>

Where can I download this part of the code now?
Thank you!

**Comment by daemonblade** [comment]
This is still an issue with 6.15.0

**Comment by maxrabbi** [comment]
Quoting from here: https://community.jaspersoft.com/jaspersoft-studio/issues/12871

> I've attached the jasperreports-eclipse-plugin-6.15.0_ce.zip file in order to make available also the other "missing" plugins.
> Probably in the future we will be able to publish also the repository "jasperreports-eclipse-plugin" like we do for the "jaspersoft-studio-ce" one.
> 
> I don't advice to build from scratch trying to create artifacts (using aggregator project), there are some further steps that needs to be performed to have some sort of raw distros.
> What you can do is put in place a development environment using the projects + target platform. In this way you can take an Eclipse and run from there the runtime JSS environment where you can play with source code.
> 
> Best regards,
> Massimo.
