### ISSUE TITLE
JusperStudio SWT base report viewer

### ISSUE THREAD

**Issue by ivanooi** [TIBCOSoftware/jaspersoft-studio-ce#31]
Hi, 

 I noticed that, JusperStudio implemented the report viewer in SWT which nicer than Swing base.
but I cannot find this control in the source code. 
and also, I notice it rendered the report nicer than Swing. 

Thanks

**Comment by maxrabbi** [comment]
Hi, I suppose that you are referring to the class _com.jaspersoft.studio.editor.preview.view.report.swt.SWTViewer_. You might want to start from there.

That said, in this page you will find generic instructions on how to setup a development environment to work with Jaspersoft Studio sources: https://community.jaspersoft.com/wiki/contributing-tibco-jaspersoft-studio-and-building-sources

Best regards,
Massimo.
