### ISSUE TITLE
Java 11: Illegal reflective access by com.jaspersoft.studio.server.utils.HttpUtils

### ISSUE THREAD

**Issue by smw-wagnerma** [TIBCOSoftware/jaspersoft-studio-ce#32]
Illegal reflective access by com.jaspersoft.studio.server.utils.HttpUtils (..../plugins/com.jaspersoft.studio.server_6.16.0.final.jar) to field java.lang.reflect.Field.modifiers

**Comment by maxrabbi** [comment]
Hi, we adopted this trick in order to overcome some issues raised with "badly named" JasperReports Server hostnames containing the '_' (underscore) char.
