### ISSUE TITLE
Support for layers

### ISSUE THREAD

**Issue by Jojs** [TIBCOSoftware/jaspersoft-studio-ce#34]
The latest release note says "Full support for JasperReports Library 6.16.0"
However, it is nearly impossible to work with layers. IReport had functionality to toggle between them. I don't see that in Studio.

**Comment by maxrabbi** [comment]
Hi, I suppose you are talking about the "Layers View" that was present in iReport. 
The feature was never implemented in Jaspersoft Studio and currently there are no actual plans to do it.
In Studio there is only the "Hide/Show band content" mechanism if you right click on a band. 

Regards,
Massimo.
