### ISSUE TITLE
JS on MacOS Big Sur - Is it possible to solve this issue?

### ISSUE THREAD

**Issue by anibalduardo** [TIBCOSoftware/jaspersoft-studio-ce#35]
https://community.jaspersoft.com/jaspersoft-studio/issues/13296/mVBIODBSCBcjBS0kNLA_-jmfJGhuPHAEVVMstOjxo28

Jaspersoft Studio doesn't work on macOS Big Sur. 
Probably eclipse or Apple issue?

**Comment by jkemp101** [comment]
Any update on this issue? Big Sur has been out for a while now and it appears the latest release of Jaspersoft Studio is unusable on it. Was hoping to start using Jasper* again after being away for many years but can't even get started with all of the UI issues on a Mac.

**Comment by maxrabbi** [comment]
> Any update on this issue? Big Sur has been out for a while now and it appears the latest release of Jaspersoft Studio is unusable on it. Was hoping to start using Jasper* again after being away for many years but can't even get started with all of the UI issues on a Mac.

Hi, please give a look at the following comment here on the Community bug tracker. It contains details on how to temporarily fix the problem.
Link: https://community.jaspersoft.com/jaspersoft-studio/issues/13296#comment-871206
