### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by gronono** [TIBCOSoftware/jaspersoft-studio-ce#37]
Hi,

Importing all projects into a brand new Eclipse "Eclipse IDE for RCP and RAP Developers" installation doesn't work.
I get a lot of compile error.

Also building via Maven don't work out of box.

Could you provide a guide to build the project from the sources ?

Regards,
Arnaud

**Comment by fud0** [comment]
I've refreshed the documentation wiki page related to the building from sources.
Give it a look here: https://community.jaspersoft.com/wiki/contributing-tibco-jaspersoft-studio-and-building-sources

Best regards,
Massimo.

**Comment by maxrabbi** [comment]
I've refreshed the documentation wiki page related to the building from sources.
Give it a look here: https://community.jaspersoft.com/wiki/contributing-tibco-jaspersoft-studio-and-building-sources

Best regards,
Massimo.
