### ISSUE TITLE
Generate EAN13+5

### ISSUE THREAD

**Issue by vevar** [TIBCOSoftware/jaspersoft-studio-ce#38]
Hello!

I didn't find any information how to generate **EAN13+5.** Maybe I missed something. I have two question.
1) How I could create EAN13+5 if it real? 
OR
2) How I could help to release it in the code? Now I'm researching sources.

Thanks!

**Comment by maxrabbi** [comment]
Hi, you might want to use the [Barcode4J Type EAN13](http://barcode4j.sourceforge.net/2.1/symbol-ean-13.html). Entering a code expression like so will work fine: "9783468111242+56789".

About contribution, please give a lookup on how to setup a development environment for Jaspersoft Studio here: https://community.jaspersoft.com/wiki/contributing-tibco-jaspersoft-studio-and-building-sources

Thanks!
Regards,
Massimo.
