### ISSUE TITLE
Solution to use URL as a datasource in jasper report

### ISSUE THREAD

**Issue by tuspatil1** [TIBCOSoftware/jaspersoft-studio-ce#57]
Hi Team,

We want to use URL(GET) as a datasource in JRXML inside JasperStudio, which requires HTTP authentication.
As per our knowledge, we can use "DataAdapter" for getting data from a remote URL. But due to some scenarios, we can not use dataadpater on the production server. 
Can you please let us know if we have any other solutions other than data adapter for our use case?

We are eagerly waiting for your reply.

Thanks,
Tushar Patil

**Comment by maxrabbi** [comment]
Hi, I assume that you might want to create a proper set of Java classes handling this scenario, including your "special" authentication and the URL reading. By the way, you did not mention if you are invoking for example a REST API returning a JSON or XML file. 

That said, once you have setup your code you could pick from the Data Adapter dialog creation a solution such as:
- "Collection of JavaBeans"
- "Custom implementation of JRDataSource"
- "JasperReports DataSource Provider class"

Regards,
Massimo.

**Comment by tuspatil1** [comment]
Thanks, Massimo, for your prompt response. 
To answer your question, we are getting an XML response from the URL. While invoking the URL, we need to perform some HTTP authentication using "Advance/Special" ways.

I tried to understand the solutions provided by you. Can you please confirm if my understanding is correct?

- "Collection of JavaBeans"
   > Need to use DataAdpater for this & we can write any HTTP authentication logic in factory classes.

- "Custom implementation of JRDataSource"
  > "No" need of Data Adapter & we can write any HTTP authentication logic in custom implementation of JRDataSource.

- "JasperReports DataSource Provider class"
  > Need to use DataAdpater for this & we can write any HTTP authentication logic in provider class.

**Comment by maxrabbi** [comment]
They are three different kind of Data Adapters at the end of the day. You will end-up having a .jrdax file containing all the details: for example pointing to your static method in case of "_Collection of JavaBeans_" one.
See this minimal example code of such a data adapter.
```
<?xml version="1.0" encoding="UTF-8" ?>
<beanDataAdapter class="net.sf.jasperreports.data.bean.BeanDataAdapterImpl">
  <name>Sample Beans Collection</name>
  <factoryClass>com.jaspersoft.studio.data.sample.SampleJRDataSourceFactory</factoryClass>
  <methodName>createBeanCollection</methodName>
  <useFieldDescription>false</useFieldDescription>
</beanDataAdapter>
```

**Comment by tuspatil1** [comment]
Thanks, Massimo, for your response. 

We have tried our usecase by creating child of "JRXmlDataSource.class" & calling JRXmlDataSource's constructor using "super()". We are using child "ReportTaskJRDataSource" class's constructor in JRXML's datasource expression.

Refer below code:
_public class ReportTaskJRDataSource extends JRXmlDataSource{
public ReportTaskJRDataSource(String url, String selectXpathExpression) throws Exception {
    	**super(new ByteArrayInputStream(getDataSource(url).getBytes()), selectXpathExpression);**
    }
   // getDataSource() is the custom method which returns XML String by consuming URL
}_

With the changes mentioned above, our usecase works perfectly fine. Can you please help us to understand if this is fine to extend "JRXmlDataSource.class" in our custom class.

**Comment by maxrabbi** [comment]
Whatever implementation is more suitable for you until is working ok, it's fine. I proposed those 3 because I did not know what could fit best.
So I assume you went with the custom implementation of JRDatasource. I don't see any special problem in extending the functionalities of the current JRXmlDataSource class. 

I will close the bug.
Regards,
Massimo.
