### ISSUE TITLE
Questions about data adapter

### ISSUE THREAD

**Issue by Billy-102** [TIBCOSoftware/jaspersoft-studio-ce#62]
Hello, I am using jaspersoft studio to create a jasper report template. However, the data cannot be displayed as expected after I configured the remote MySQL server, could you give me some suggestions?

**Comment by gt78** [comment]
Hi Billy, did you try to preview the data from the query dialog?

**Comment by Billy-102** [comment]
![image](https://user-images.githubusercontent.com/94583069/225325677-06663755-38ce-4dca-a50c-0bccd59633d3.png)


This is what I have seen in the wizard, I guess the database has not been accessed.

**Comment by gt78** [comment]
Did you test your connection from the Data Adapter dialog?

**Comment by Billy-102** [comment]
oh, I have not tested it

**Comment by Billy-102** [comment]
![image](https://user-images.githubusercontent.com/94583069/225542225-af291181-bb35-4ccb-9365-f6bf02222d1a.png)

This is the test result. How should I fix it?

**Comment by gt78** [comment]
It looks like you are trying to connect to a Microsoft SQLServer (this is the driver you selected), but probably what you want is the driver for MySql like you said in your first post, which is MariaDB (org.mariadb.jdbc.Driver).

**Comment by gt78** [comment]
Hi Billy, the exception seems pretty clear: the connection failed, probably you are not able to access that host/port?

**Comment by gt78** [comment]
by the way, Billy, the port 1433 is the default DB port for a Microsoft SQL Database, not a MySql/Maria database. If MS SQLServer is the DB you are trying to use, you should add your Microsoft JDBC driver, or use the open source version of the driver shipped with Jaspersoft Studio (MS SQLServer (net.sourceforge.jtds.jdbc.Driver)).
