### ISSUE TITLE
Is there any data adapter for apache cassandra?

### ISSUE THREAD

**Issue by Jakk-y** [TIBCOSoftware/jaspersoft-studio-ce#63]
In the application I can't find any adapter already installed for cassandra. I found this https://community.jaspersoft.com/project/cassandra-connector/releases but I am not able to download the files and I can't find anything about it on the web.

**Comment by gt78** [comment]
Hi Jakk-y, you should use a JDBC driver bridge for Cassandra (which will act as bridge between Cassandra and any JDBC compliant tools). The data source you are trying to download is actually for JasperReports Server and you don't need it in Jaspersoft Studio.

**Comment by maxrabbi** [comment]
Hi Jakk-y, as Giulio suggested you should try with a dedicated JDBC driver and in Studio create a standard JDBC data adapter adding the dedicated jar(s). 
From an historical point-of-view the dedicated data-adapter plug-in we had was removed many versions ago from the CE (version 6.6.0).
