### ISSUE TITLE
Compatibility Question for JasperReports Library 6.7.1 and Jaspersoft Studio

### ISSUE THREAD

**Issue by geftsu** [TIBCOSoftware/jaspersoft-studio-ce#74]
Hallo!

Our project uses jasperreports library version 6.7.1 for report generation. I wasn't able to find a matching version of Jaspersoft Studio (in this repo 6.7.0 doesn't seem to exist, for example). 

Since more modern versions of Jaspersoft Studio are usually capable of interacting with previous library versions, if set up properly, I looked through the properties of the latest version (6.20.6 at the time of writing) and discovered that 6.7.1 version of .jrxml cannot be selected, the option is missing. In fact, several versions seem to be missing. I have attached a screenshot for reference.

![Screenshot from 2023-11-14 08-36-15](https://github.com/TIBCOSoftware/jaspersoft-studio-ce/assets/114946441/099500b0-784b-4ba6-98a0-a7cdad8030aa)

Do you know what's up with those versions? Is it okay to simply use the closest  earlier version in this case?

Thanks in advance!

**Comment by gt78** [comment]
When a version is missing, it means that it does not introduce any incompatibility, this means that you can safely use max version <= of the version you need.

**Comment by geftsu** [comment]
Thank you very much for the response! Just wanted to make sure.
