### ISSUE TITLE
Data Adapter response HTTP 436

### ISSUE THREAD

**Issue by sozcos** [TIBCOSoftware/jaspersoft-studio-ce#76]
Jaspersoft studio 6.20.6

When I use JSON File type data adapters, when I execute dataset and query in my project, it gives me the following error: net.sf.jasperreports.engine.

```
net.sf.jasperreports.engine.JRRuntimeException: Response has status code HTTP/1.1 436 <none>.
	at net.sf.jasperreports.data.http.HttpDataConnection.getInputStream(HttpDataConnection.java:86)
	at net.sf.jasperreports.data.DataFileStream.<init>(DataFileStream.java:47)
	at net.sf.jasperreports.data.DataFileUtils.getDataStream(DataFileUtils.java:62)
	at com.jaspersoft.studio.data.querydesigner.json.JsonDataManager.loadJsonDataFile(JsonDataManager.java:86)
	at com.jaspersoft.studio.data.querydesigner.json.JsonQueryDesigner$JsonLoaderJob.run(JsonQueryDesigner.java:393)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

My URL in the browser can correctly return json content, and I do not set the relevant blocking rules, please I want to solve this problem

![image](https://github.com/TIBCOSoftware/jaspersoft-studio-ce/assets/87360050/559fa9cd-3869-4e64-ac23-4f4f37874eed)
![image](https://github.com/TIBCOSoftware/jaspersoft-studio-ce/assets/87360050/8472ee11-5888-4b39-805c-6217602ad19e)

**Comment by sozcos** [comment]
![image](https://github.com/TIBCOSoftware/jaspersoft-studio-ce/assets/87360050/42f2b4f4-4615-41ce-9a07-87bfebcba67f)

**Comment by gt78** [comment]
HTTP 436 error does not even exist. You should check if the server expect specific http headers, and add the to the request (i.e. Accept: application/json). Being a simple GET request, I would also try to set the whole url included the parameter, without using the parameters box and see if this helps.

**Comment by maxrabbi** [comment]
Hi, if possible please attach the sample report, DA details (or export it as file) and the json data you are returning.
As Giulio said this 436 http return code does not exist. I can only assume it's a server side typo and it is possibly a 426.
What is the http server (and version) you are using? 

This information might help trying to reproduce the same scenario on our side.
Regards,
Massimo.

**Comment by sozcos** [comment]
Thanks for your replies, I also tried the url include parameter way, but still appear abnormal, I further test found that, in the sub.jrxml execution da query is normal, when I switched to the parent.jrxml execution da query appeared in the above picture error, but the strange thing is that, today I would like to reproduce the problem again when it is normal again! , but I still provide my data to you, my server http version is HTTP/1.1

[436 problem.zip](https://github.com/TIBCOSoftware/jaspersoft-studio-ce/files/13655340/436.problem.zip)

**Comment by sozcos** [comment]
If I take back that it's working again, just now it's 436 again, when executing da in parent.jrxml.

**Comment by sozcos** [comment]
Whenever this exception occurs I have to restart jaspersoft studio to get it to work, and if I change the url parameter, I also get the 436 error.

**Comment by sozcos** [comment]
Also, I was wondering if it is possible to manually enter parameters in dataset and query in addition to manually filling in url parameters in da? Currently, dataset and query query parameters are only available as dropdown options, which is a bit inconvenient for me.

**Comment by gt78** [comment]
Hi sozcos,
I think you should first investigate why do you get this strange 436 http error. This error comes from the server. I would suggest you to try simulating the request that the data adapter executes with some tool like Postman. Jaspersoft Studio allows you to manipulate the request in all shapes and forms, so you should find the settings that work for you (mostly related to request headers information).

I'm not sure if I understood your second question, but there is a way to dynamically set values for data adapter request parameters. You can configure them by passing, for instance, the value of a parameter.
Where using a remote data adapter, you should be able to see a Data Adapter tab in the query dialog, this is where you can bind report parameters and request parameters:

![image](https://github.com/TIBCOSoftware/jaspersoft-studio-ce/assets/11684147/13b42560-d655-40c3-a686-1c9b46dde9f4)

**Comment by sozcos** [comment]
Thank you very much for your reply, also I would like to know, every time I add a field through da, my original field list will be cleared, how can I operate so that my original existing fields will not be cleared?
