### ISSUE TITLE
Cannot switch List view and Report view

### ISSUE THREAD

**Issue by mvcoile** [TIBCOSoftware/jaspersoft-studio-ce#8]
When I go into a List view, I can no longer go to the report view. While the outline does udate, the "Design" view is stuck on the List view.

See: https://cl.ly/0d39d397e40a

**Comment by maxrabbi** [comment]
Hi bug is fixed in the latest version 6.10.0.
There is also a Community Bug related to it:
- https://community.jaspersoft.com/jaspersoft-studio/issues/11961
